### ISSUE TITLE
move from spray to akka-http

### ISSUE THREAD

**Issue by antonkulaga** [broadinstitute/lenthall#30]
Spray is dead and akka-http is a future version of spray. Your dependency on spray blocks me from adding Scala 2.12 support. Please, consider moving to akka-http

**Comment by geoffjentry** [comment]
You'll notice that we're slowly doing that. The big challenge is that our usage of spray inside cromwell is pathologically insane and doesn't map well to akka-http. 

2.12 is also something that I want to do (it's at the top of the personal todo list I mentioned yesterday), we're getting there. I didn't realize there wasn't a 2.12 artifact for spray though, blech.

**Comment by antonkulaga** [comment]
> I didn't realize there wasn't a 2.12 artifact for spray though, blech.

And I think it will never be, spray is dead and people are moving to akka-http + akka-streams.

**Comment by geoffjentry** [comment]
Yeah I double checked the other day and saw a post from Konrad confirming. I had been viewing the 2.12 upgrade as a smaller project than spray -> akka-http, but since it's now clear the latter is a dependency on the former I guess the difference is academic.

**Comment by antonkulaga** [comment]
Repushed. Look now.

**Comment by geoffjentry** [comment]
@antonkulaga Closing this as per #32. We're removing the spray code altogether as cromwell is the only software we use which depends on it. #32 does that and upgrades to 2.12
