### ISSUE TITLE
Adding conversion from Option[A] to ErrorOr[A].

### ISSUE THREAD

**Issue by curoli** [broadinstitute/lenthall#38]
Add toErrorOr, analogous to lenthall.validation.Validation.TryValidation.toErrorOr, but with extra String argument providing error message in case of None.

**Comment by danbills** [comment]
See [`toValidNel`](https://github.com/typelevel/cats/blob/master/core/src/main/scala/cats/syntax/option.scala#L113)

**Comment by curoli** [comment]
Close, but not quite. toValidNel[String] appears to create a Validated[NonEmptyList[A], String], but we need ErrorOr[A], which is a Validated[NonEmptyList[String], A].

**Comment by curoli** [comment]
You can get an ErrorOr[A] using
toValid(NonEmptyList.of(myString))
is that good enough or is it worth to create a convenience method?

**Comment by curoli** [comment]
I implemented conversion from Option[A] to ErrorOr[A]. I just need permission to push and create a PR.

**Comment by mcovarr** [comment]
using Cats toValidNel instead
